# Generated by Django 4.2.24 on 2025-10-22 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('catalog_number', models.CharField(blank=True, max_length=128)),
                ('formats', models.TextField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thumb', models.URLField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('release_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, choices=[('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('G+', 'Good Plus'), ('VG', 'Very Good'), ('VG+', 'Very Good Plus'), ('NM', 'Near Mint'), ('M', 'Mint')], max_length=4)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
