# Generated by Django 4.2.24 on 2025-10-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_migrate_suggested_to_price'),
        ('accounts', '0003_listingimage'),
    ]

    operations = [
    ]
