# Generated by Django - add contact_preference to Message
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message_reply_replyimage_messageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], help_text='Preferred contact method for non-registered users', max_length=10),
        ),
    ]
