# Generated by Django 4.2.24 on 2025-10-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_contact_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
