# Generated by Django 4.2.24 on 2025-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Null = unlimited/unknown, 0 = out of stock', null=True),
        ),
    ]
